server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexanderIab/planner-config-mc
          basedir: file://C:/git-config-planner
          clone-on-start: true
          username: AlexanderIab
          password: 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
          default-label: main